#!/usr/bin/env node
/**
 * Shared path constants for CJS hooks.
 *
 * Reads core/paths.json (generated by `python3 core/paths.py`).
 * Falls back to hardcoded PARA structure if the JSON doesn't exist.
 */
const fs = require('fs');
const path = require('path');

const VAULT_ROOT = process.env.CLAUDE_PROJECT_DIR || process.env.VAULT_PATH || process.cwd();

/**
 * Load vault path constants from core/paths.json, falling back to hardcoded PARA defaults.
 * @returns {Record<string, string>} Object mapping path constant names to absolute directory/file paths
 */
function loadPaths() {
  // Try generated JSON first
  const jsonPath = path.join(VAULT_ROOT, 'core', 'paths.json');
  if (fs.existsSync(jsonPath)) {
    try {
      return JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
    } catch (e) {
      // Fall through to hardcoded defaults
    }
  }

  // Hardcoded fallback (mirrors core/paths.py)
  return {
    VAULT_ROOT,
    INBOX_DIR: path.join(VAULT_ROOT, '00-Inbox'),
    QUARTER_GOALS_DIR: path.join(VAULT_ROOT, '01-Quarter_Goals'),
    WEEK_PRIORITIES_DIR: path.join(VAULT_ROOT, '02-Week_Priorities'),
    TASKS_DIR: path.join(VAULT_ROOT, '03-Tasks'),
    PROJECTS_DIR: path.join(VAULT_ROOT, '04-Projects'),
    AREAS_DIR: path.join(VAULT_ROOT, '05-Areas'),
    RESOURCES_DIR: path.join(VAULT_ROOT, '06-Resources'),
    ARCHIVES_DIR: path.join(VAULT_ROOT, '07-Archives'),
    MEETINGS_DIR: path.join(VAULT_ROOT, '00-Inbox', 'Meetings'),
    IDEAS_DIR: path.join(VAULT_ROOT, '00-Inbox', 'Ideas'),
    DAILY_PLANS_DIR: path.join(VAULT_ROOT, '00-Inbox', 'Daily_Plans'),
    TASKS_FILE: path.join(VAULT_ROOT, '03-Tasks', 'Tasks.md'),
    QUARTER_GOALS_FILE: path.join(VAULT_ROOT, '01-Quarter_Goals', 'Quarter_Goals.md'),
    WEEK_PRIORITIES_FILE: path.join(VAULT_ROOT, '02-Week_Priorities', 'Week_Priorities.md'),
    PEOPLE_DIR: path.join(VAULT_ROOT, '05-Areas', 'People'),
    COMPANIES_DIR: path.join(VAULT_ROOT, '05-Areas', 'Companies'),
    CAREER_DIR: path.join(VAULT_ROOT, '05-Areas', 'Career'),
    EVIDENCE_DIR: path.join(VAULT_ROOT, '05-Areas', 'Career', 'Evidence'),
    INTEL_DIR: path.join(VAULT_ROOT, '06-Resources', 'Intel'),
    MEETING_INTEL_DIR: path.join(VAULT_ROOT, '06-Resources', 'Intel', 'Meeting_Intel'),
    SYSTEM_DIR: path.join(VAULT_ROOT, 'System'),
    PILLARS_FILE: path.join(VAULT_ROOT, 'System', 'pillars.yaml'),
    USER_PROFILE_FILE: path.join(VAULT_ROOT, 'System', 'user-profile.yaml'),
    PEOPLE_INDEX_FILE: path.join(VAULT_ROOT, 'System', 'People_Index.json'),
  };
}

module.exports = { loadPaths };
